name: CI TalentoTech

#DISPARADORES O EVENTOS (CUANDO SE EJECUTA)
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    
#TAREA A REALIZAR
jobs:
  test:
    runs-on: ubuntu-latest
    env: #Variables de entorno
      PYTHON_VERSION: '3.13'
      PIP_CACHE: ~/.cache/pip

    #PASOS DE LA TAREA
    steps:
      # 1️⃣ Checkout
      - name: Checkout codigo
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }} #tambien se puede poner directamente 3.13

      # 3️⃣ Cache pip
      - name: Cache dependencias pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE }} #Se usa la variable de entorno PIP_CACHE para dar la ruta
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Instalar dependencias
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # 5️⃣ Ejecutar tests
      - name: Ejecutar tests
        run: python run_tests.py

      # 6️⃣ Crear carpetas
      - name: Crear carpetas si no existen
        run: mkdir -p reports logs  

      # 7️⃣ Subir artefactos
      - name: Subir HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/

      - name: Subir logs
        uses: actions/upload-artifact@v4
        with:
          name: suite-log
          path: logs/
